### ISSUE TITLE
Exceptions cause application to crash

### ISSUE THREAD

**Issue by devfxplayer** [Code-Sharp/WampSharp#102]
I have an application that send 50 messages per second to 50 clients and has many connections and disconnectios of clients. I get all the time this exceptions that cause the application to crash:

Ex 1:
System.IO.IOException: Unable to write data to the transport connection: An existing connection was forcibly closed by the remote host. ---> System.Net.Sockets.SocketException: An existing connection was forcibly closed by the remote host
   at System.Net.Sockets.Socket.EndSend(IAsyncResult asyncResult)
   at System.Net.Sockets.NetworkStream.EndWrite(IAsyncResult asyncResult)
   --- End of inner exception stack trace ---
   at System.Net.Sockets.NetworkStream.EndWrite(IAsyncResult asyncResult)
   at System.Threading.Tasks.TaskFactory`1.FromAsyncCoreLogic(IAsyncResult iar, Func`2 endFunction, Action`1 endAction, Task`1 promise, Boolean requiresSynchronization)
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)

Ex 2:
System.Net.Sockets.SocketException (0x80004005): An existing connection was forcibly closed by the remote host
   at System.Net.Sockets.Socket.EndSend(IAsyncResult asyncResult)
   at System.Net.Sockets.NetworkStream.EndWrite(IAsyncResult asyncResult)

**Comment by darkl** [comment]
I need some sample code that reproduces this. Please upload a sample to
github gist.

**Comment by darkl** [comment]
FWIW, [these load tests](https://github.com/darkl/WampSharpTests) written by @nj4x don't crash on latest version.

**Comment by devfxplayer** [comment]
```javascript
      public void Start(string host, int port)
     {
            string serverAddress = "ws://" + host + ":" + port + "/ws";
            _server = new DefaultWampHost(serverAddress);
            _server.Open();            
            var realm = _server.RealmContainer.GetRealmByName(Realm);
            
            realm.SessionCreated += SessionCreated;
            realm.SessionClosed += SessionClosed;
            realm.TopicContainer.TopicCreated += TopicCreated;
            realm.TopicContainer.TopicRemoved += TopicRemoved;

            if (!string.IsNullOrWhiteSpace(Subject))
            {
                realm.TopicContainer.CreateTopicByUri(Subject, false);
                _subject = realm.Services.GetSubject<string>(Subject);
            }
     }

        private void TopicRemoved(object sender, WampTopicRemovedEventArgs e)
        {
            if (OnTopicRemoved != null)
                OnTopicRemoved(e.Topic.TopicUri);
        }

        void TopicCreated(object sender, WampTopicCreatedEventArgs e)
        {
            if (OnTopicCreated != null)
                OnTopicCreated(e.Topic.TopicUri);
        }

        void SessionClosed(object sender, WampSessionCloseEventArgs e)
        {
            Interlocked.Decrement(ref _count);           
        }

        
        void SessionCreated(object sender, WampSessionEventArgs e)
        {
            Interlocked.Increment(ref _count);
        }

    public void Send(List<object> list)
     {
     var json = new JsonMessage
     {
         Messages = list
     };

    _subject.OnNext(message.ToJson());
      }

```

**Comment by darkl** [comment]
Sorry, I can't use this sample. It is far from being complete (there are no publications here nor client code, and the code doesn't even compile). You might want to fork [this sample project](https://github.com/darkl/WampSharpTests) and modify it so it reproduces the crash. You are also invited to create your own repository with a simple sample project that reproduces the crash. Without suitable reproduce code I can't help much.

**Comment by devfxplayer** [comment]
ok  will fork

**Comment by darkl** [comment]
@devfxplayer any updates on this?

**Comment by devfxplayer** [comment]
Not yet will do soon

**Comment by devfxplayer** [comment]
Hi, I was not able to fork, but I was able to update to latest version, I am now facing extreme memory usage, (up to 2GB) with out storing anything in memory.

**Comment by darkl** [comment]
Hi @devfxplayer,

I need some full standalone sample for these issues. Can't do much with this description alone.

Elad

**Comment by devfxplayer** [comment]
you mean the problem is in my code?

**Comment by darkl** [comment]
I'm not saying the problem is in your code, but in order to investigate
this issue I need some code that you claim that leaks in order to analyze
its memory and investigate the problem.

**Comment by devfxplayer** [comment]
ok, using ANTS Memory profiler I have found that all strings get retain in my memory.
I am sending json strings.
I will try to remove some app logic and upload some code

**Comment by devfxplayer** [comment]
this code uses the code above
     
    private WampWebSocketServer _webSocketServer;
   
    private void Send(object message)
        {
			
			var msg = message.FromJson<JsonMessage>();

            if (msg == null)
                return;
						                                       
			var json = new JsonMessage
			{
				MessageType = MessageType.JSON,
				Messages = msg
			};

			_webSocketServer.Send(json);
            
		}

and I have added the following method in code above:

     public void Send(IMessage message)
        {
            _realm.TopicContainer.GetOrCreateTopicByUri(Subject);
            _subject.OnNext(message.ToJson());
        }

**Comment by darkl** [comment]
Can you please include a complete program that compiles (including a Main
entry)?

It can really help!

Please create a simple Console Application in a single .cs file and upload
it to GitHub gist so I can investigate this.

Elad

**Comment by devfxplayer** [comment]
what is GitHub gist?

**Comment by darkl** [comment]
http://gist.github.com

**Comment by devfxplayer** [comment]
which version did not cause those crashes before 1.2.2.11-beta?

**Comment by darkl** [comment]
Dear @fxplayer,

I can't help you because you haven't provided yet a full working example
which reproduces any of the problems you mention.

I'm not aware of any of the crashes you claim, so I can't point on a
version with or without these crashes.

I'd really like to help you but I can't guess how to cause these crashes
myself.

Please provide code that reproduces the problems you claim of and I promise
I'll do my best to try to help.

Elad

**Comment by darkl** [comment]
Closing due to inactivity.
