### ISSUE TITLE
Exception on Subscription over MsgPack Channel

### ISSUE THREAD

**Issue by whipit** [Code-Sharp/WampSharp#146]
I get the below exception when I try to subscribe to a topic over a MsgPack channel.

Has anyone encountered this before?

Thanks

Tim

My code
`
DefaultWampChannelFactory factory = new DefaultWampChannelFactory();
m_channel = factory.CreateMsgpackChannel(ServerUrl, Realm);
WampSharp.V2.Client.IWampRealmProxy realmProxy = m_channel.RealmProxy;
realmProxy.Monitor.ConnectionBroken += Monitor_ConnectionBroken;
realmProxy.Monitor.ConnectionError += Monitor_ConnectionError;
realmProxy.Monitor.ConnectionEstablished += Monitor_ConnectionEstablished;
WampSharp.V2.Client.IWampRealmProxy realmProxy = m_channel.RealmProxy;
var subject = realmProxy.Services.GetSubject(m_topic);
`

Exception Stack Trace:
System.TypeInitializationException: The type initializer for 'System.Reactive.Linq.Observable' threw an exception. ---> System.TypeInitializationException: The type initializer for 'System.Reactive.Linq.QueryServices' threw an exception. ---> System.TypeInitializationException: The type initializer for 'System.Reactive.PlatformServices.PlatformEnlightenmentProvider' threw an exception. ---> System.IO.FileLoadException: Could not load file or assembly 'System.Reactive.PlatformServices, Version=3.0.0.0, Culture=neutral, PublicKeyToken=94bc3704cddfc263' or one of its dependencies. The located assembly's manifest definition does not match the assembly reference. (Exception from HRESULT: 0x80131040)
   at System.RuntimeTypeHandle.GetTypeByName(String name, Boolean throwOnError, Boolean ignoreCase, Boolean reflectionOnly, StackCrawlMarkHandle stackMark, IntPtr pPrivHostBinder, Boolean loadTypeFromPartialName, ObjectHandleOnStack type)
   at System.RuntimeTypeHandle.GetTypeByName(String name, Boolean throwOnError, Boolean ignoreCase, Boolean reflectionOnly, StackCrawlMark& stackMark, IntPtr pPrivHostBinder, Boolean loadTypeFromPartialName)
   at System.RuntimeType.GetType(String typeName, Boolean throwOnError, Boolean ignoreCase, Boolean reflectionOnly, StackCrawlMark& stackMark)
   at System.Type.GetType(String typeName, Boolean throwOnError)
   at System.Reactive.PlatformServices.PlatformEnlightenmentProvider.CreatePlatformProvider()
   at System.Reactive.PlatformServices.PlatformEnlightenmentProvider..cctor()
   --- End of inner exception stack trace ---
   at System.Reactive.PlatformServices.PlatformEnlightenmentProvider.get_Current()
   at System.Reactive.Linq.QueryServices.Initialize()
   at System.Reactive.Linq.QueryServices..cctor()
   --- End of inner exception stack trace ---
   at System.Reactive.Linq.QueryServices.GetQueryImpl[T](T defaultInstance)
   at System.Reactive.Linq.Observable..cctor()
   --- End of inner exception stack trace ---
   at System.Reactive.Linq.Observable.FromEventPattern[TEventArgs](Action`1 addHandler, Action`1 removeHandler)
   at WampSharp.V2.WampClientSubject.CreateObservable(IWampTopicProxy topic, IWampClientConnectionMonitor monitor)
   at WampSharp.V2.WampClientSubject..ctor(IWampTopicProxy topic, IWampClientConnectionMonitor monitor)
   at WampSharp.V2.WampRealmProxyServiceProvider.GetSubject(String topicUri)

**Comment by whipit** [comment]
Please ignore.   I clearly cannot read well.    I was missing a DLL "System.Reactive.PlatformServices".
