### ISSUE TITLE
Seems WampException.Details must not be null

### ISSUE THREAD

**Issue by nj4x** [Code-Sharp/WampSharp#162]
I've found small incompatibility issue of WampSharp client and crossbar.io wamp router:

In case we pass invalid method argument, WampSharp generates WampInvalidArgumentException which can not be deserialized by crossbar.io (latest version 16.10.1), it throws ProtocolError and drops the connection:

2016-12-14T00:37:49-0800 [Router      30195] Traceback (most recent call last):
  File "/opt/crossbar/site-packages/autobahn/wamp/websocket.py", line 88, in onMessage
    for msg in self._serializer.unserialize(payload, isBinary):
  File "/opt/crossbar/site-packages/autobahn/wamp/serializer.py", line 131, in unserialize
    msg = Klass.parse(raw_msg)
  File "/opt/crossbar/site-packages/autobahn/wamp/message.py", line 1006, in parse
    details = check_or_raise_extra(wmsg[3], u"'details' in ERROR")
  File "/opt/crossbar/site-packages/autobahn/wamp/message.py", line 207, in check_or_raise_extra
    raise ProtocolError(u"{0}: invalid type {1}".format(message, type(value)))
ProtocolError: 'details' in ERROR: invalid type <type 'NoneType'>

The following amendment of WampException.cs has resolved the issue:

line 93:                 return mDetails ?? mEmptyDetails;

i.e.
        public IDictionary<string, object> Details
        {
            get
            {
                return mDetails ?? mEmptyDetails;
            }
        }

**Comment by darkl** [comment]
Thanks for the catch!
