### ISSUE TITLE
Wss does not work

### ISSUE THREAD

**Issue by devfxplayer** [Code-Sharp/WampSharp#191]
I am trying to to use wss and it does not work:    

       Address = secure ? $"wss://{host}:{port}/ws" : $"ws://{host}:{port}/ws";
            if (secure)
            {
                var cert = new X509Certificate2(certPath, password);
                _server = new DefaultWampHost(Address, cert);
            }
            else
            {
                _server = new DefaultWampHost(Address);
            }
            _server.Open();

autobahnjs:

       var connection = new autobahn.Connection({
                    url: config.adminEndpoint, //'wss://' + ip + ':23023/
                    realm: config.realm,
                });

on dev machine i get this log:

First Chance Exception - The handshake failed due to an unexpected packet format. 
System.IO.IOException: The handshake failed due to an unexpected packet format.
   at System.Net.Security.SslState.StartReadFrame(Byte[] buffer, Int32 readBytes, AsyncProtocolRequest asyncRequest)

**Comment by darkl** [comment]
@stevenbonepgh

**Comment by StevenBonePgh** [comment]
Works for me - WAMP1, anyway.  I'd suggest using different ports for secure and not secure. Your client should also specify wss: - usually the exception you are seeing is due to one side being secure and the other not.

**Comment by devfxplayer** [comment]
I did specify wss on the client. I am using WAMP2. 
When I use ws  it works but the wws does not. No errors on server when initiating.
I am also using the same certificate on web server (azure) and on window service.

**Comment by darkl** [comment]
I checked the code and the Fleck transport SSL setup is the same for WAMP1 and WAMP2.

@esso23 asked [a question](https://github.com/Code-Sharp/WampSharp/issues/149) about wss before. Maybe he can help?

**Comment by devfxplayer** [comment]
hi @esso23
I have a pfx cert running on both sides. 
did you find out something that I need to do?

**Comment by darkl** [comment]
Closing due to inactivity. Please comment here with your findings.

**Comment by devfxplayer** [comment]
hi any update on the matter?

**Comment by devfxplayer** [comment]
thanks but we are not looking for client, we want to setup a C# router with autobahnjs client. Also we are not using self-signed certs but signed by certificate authorities.

**Comment by darkl** [comment]
Oops.

The code should work as is. You might want to try a to setup plain Fleck
websockets server application with your certificate and see if that works.

If you do that, please share your Fleck code so I can see if anything is
missing from the WampSharp implementation.

Elad

**Comment by devfxplayer** [comment]
The following works  on IIS web app using the same cert.pfx on the binding

    var serverSec = new WebSocketServer("wss://0.0.0.0:8431");
            serverSec.Certificate = new X509Certificate2("cert.pfx", "password");
            serverSec.Start(socket =>
            {
                socket.OnOpen = () => Console.WriteLine("Open!");
                socket.OnClose = () => Console.WriteLine("Close!");
                socket.OnMessage = message =>
                {
                    Console.WriteLine(message);                    
                    socket.Send(message);
                };
            });

**Comment by devfxplayer** [comment]
Some more info
   10:40:46,911 ERROR First Chance Exception - The handshake failed due to an unexpected packet format. 
System.IO.IOException: The handshake failed due to an unexpected packet format.
   at System.Net.Security.SslState.StartReadFrame(Byte[] buffer, Int32 readBytes, AsyncProtocolRequest asyncRequest)
 10:40:46,928 ERROR First Chance Exception - The handshake failed due to an unexpected packet format. 
System.IO.IOException: The handshake failed due to an unexpected packet format.
   at System.Net.Security.SslState.InternalEndProcessAuthentication(LazyAsyncResult lazyResult)

**Comment by darkl** [comment]
@devfxplayer we also set the same property of Fleck WebSocketServer, see [here](https://github.com/Code-Sharp/WampSharp/blob/dc6b466f17ff767eee2da267a951b0d9c2d70650/src/net45/Default/WampSharp.Fleck/Fleck/FleckWebSocketTransport.cs#L73).

Elad

**Comment by devfxplayer** [comment]
protected override string GetSubProtocol(IWebSocketConnection connection)
        {
            string protocol = connection.ConnectionInfo.NegotiatedSubProtocol;
            return protocol;
        }

returns null and then breaks the follwing line@

     if (mBindings.TryGetValue(protocol, out listener))

**Comment by darkl** [comment]
Why does it return null? Can you add the HTTP request headers sent from the client side (you can see it in developer console in Chrome under the WebSocket connection).

Elad

**Comment by devfxplayer** [comment]
Request URL:wss://domain.local:23026/
Request Headers
Provisional headers are shown
Accept-Encoding:gzip, deflate, br
Accept-Language:en-GB,en;q=0.8,en-US;q=0.6,el;q=0.4
Cache-Control:no-cache
Connection:Upgrade
Cookie:ASPSESSIONIDSCBSDBTS=APGJAJCDBOGHKJMLIKNIOCHA; ASP.NET_SessionId=mwhya22i2itfhj1rg5l4rpa2; i18next=en; _ga=GA1.2.1047271981.1486650846; _gid=GA1.2.344701658.1506935101; ASPSESSIONIDSGBSDBTS=FAHJAJCDOOHPKIPGIHBDEFKL
Host:domain.local:23026
Origin:https://domain.local
Pragma:no-cache
Sec-WebSocket-Extensions:permessage-deflate; client_max_window_bits
Sec-WebSocket-Key:oLgNsVCY3vIaqgRQZJMG0A==
Sec-WebSocket-Version:13
Upgrade:websocket
User-Agent:Mozilla/5.0 (Windows NT 6.1; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/61.0.3163.100 Safari/537.36

**Comment by darkl** [comment]
Not Sec-WebSocket-Protocol is defined. A typical request is supposed to
look like this:


   1. Accept-Encoding:
      gzip, deflate, br
      2. Accept-Language:
      en-US,en;q=0.8,he;q=0.6
      3. Cache-Control:
      no-cache
      4. Connection:
      Upgrade
      5. Cookie:
      _ga=GA1.2.706924685.1506955546; _gid=GA1.2.1472371248.1506955546;
      _gat=1
      6. Host:
      demo.crossbar.io
      7. Origin:
      https://crossbar.io
      8. Pragma:
      no-cache
      9. Sec-WebSocket-Extensions:
      permessage-deflate; client_max_window_bits
      10. Sec-WebSocket-Key:
      c+VLaWTAW+jic6LPbc7roA==
      11. Sec-WebSocket-Protocol:
      wamp.2.json
      12. Sec-WebSocket-Version:
      13
      13. Upgrade:
      websocket
      14. User-Agent:
      Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML,
      like Gecko) Chrome/61.0.3163.100 Safari/537.36

Name

ws

**Comment by devfxplayer** [comment]
can you send the code that created this header?

**Comment by darkl** [comment]
```javascript
connection = new autobahn.Connection({
  url: url,
  realm: realm
});
 

```

**Comment by devfxplayer** [comment]
thanks it works, i was missing the /ws
