### ISSUE TITLE
Unhandeled exception

### ISSUE THREAD

**Issue by seba-0** [Code-Sharp/WampSharp#193]
Closing tcp connection forcibly can lead to unhandled exception. To reproduce problem connect to any server as subscriber. Then in some tool as TCPView close conection to server you subscribed to. This will throw exception like:
An unhandled exception occurred WampSharp.V2.Core.Contracts.WampConnectionBrokenException: Connection got broken. CloseType:Disconnection
   at System.Reactive.PlatformServices.ExceptionServicesImpl.Rethrow(Exception exception)
   at System.Reactive.Stubs.<>c.<.cctor>b__2_1(Exception ex)
   at System.Reactive.AnonymousSafeObserver`1.OnError(Exception error)
   at System.Reactive.Linq.ObservableImpl.Merge`1._.Iter.OnError(Exception error)
   at System.Reactive.Linq.ObservableImpl.SelectMany`2._.Iter.OnError(Exception error)
   at System.Reactive.Linq.ObservableImpl.Throw`1._.Invoke()
   at System.Reactive.Concurrency.Scheduler.Invoke(IScheduler scheduler, Action action)
   at System.Reactive.Concurrency.ImmediateScheduler.Schedule[TState](TState state, Func`3 action)
   at System.Reactive.Concurrency.Scheduler.Schedule(IScheduler scheduler, Action action)
   at System.Reactive.Linq.ObservableImpl.Throw`1._.Run()
   at System.Reactive.Linq.ObservableImpl.Throw`1.Run(IObserver`1 observer, IDisposable cancel, Action`1 setSink)
   at System.Reactive.Producer`1.Run(IScheduler _, State x)
   at System.Reactive.Concurrency.ScheduledItem`2.InvokeCore()
   at System.Reactive.Concurrency.CurrentThreadScheduler.Trampoline.Run(SchedulerQueue`1 queue)
   at System.Reactive.Concurrency.CurrentThreadScheduler.Schedule[TState](TState state, TimeSpan dueTime, Func`3 action)
   at System.Reactive.Concurrency.LocalScheduler.Schedule[TState](TState state, Func`3 action)
   at System.Reactive.Producer`1.SubscribeRaw(IObserver`1 observer, Boolean enableSafeguard)
   at System.ObservableExtensions.SubscribeSafe[T](IObservable`1 source, IObserver`1 observer)
   at System.Reactive.Linq.ObservableImpl.SelectMany`2._.SubscribeInner(IObservable`1 inner)
   at System.Reactive.Linq.ObservableImpl.SelectMany`2._.OnNext(TSource value)
   at System.Reactive.Subjects.Subject`1.OnNext(T value)
   at System.Reactive.Linq.ObservableImpl.FromEventPattern.Impl`2.<>c__DisplayClass3_0.<GetHandler>b__1(Object sender, TEventArgs eventArgs)
   at System.EventHandler`1.Invoke(Object sender, TEventArgs e)
   at WampSharp.V2.Client.WampSessionClient`1.OnConnectionBroken(WampSessionCloseEventArgs e)
   at WampSharp.V2.Client.WampSessionClient`1.RaiseConnectionBroken()
   at WampSharp.V2.Client.WampSessionClient`1.OnConnectionClosed()
   at WampSharp.V2.Client.WampChannel`1.OnConnectionClosed(Object sender, EventArgs e)
   at WampSharp.Core.Listener.ReviveClientConnection`1.RaiseConnectionClosed()
   at WampSharp.Core.Listener.ReviveClientConnection`1.OnConnectionClosed(Object sender, EventArgs e)
   at WampSharp.WebSocket4Net.WebSocket4NetConnection`1.RaiseConnectionClosed()
   at WampSharp.WebSocket4Net.WebSocket4NetConnection`1.WebSocketOnClosed(Object sender, EventArgs eventArgs)
   at WebSocket4Net.WebSocket.FireClosed()
   at WebSocket4Net.WebSocket.OnClosed()
   at WebSocket4Net.WebSocket.client_Closed(Object sender, EventArgs e)
   at SuperSocket.ClientEngine.ClientSession.OnClosed()
   at SuperSocket.ClientEngine.SslStreamTcpSession.OnDataRead(IAsyncResult result)
   at System.Net.LazyAsyncResult.Complete(IntPtr userToken)
   at System.Net.LazyAsyncResult.ProtectedInvokeCallback(Object result, IntPtr userToken)
   at System.Net.Security._SslStream.StartFrameBody(Int32 readBytes, Byte[] buffer, Int32 offset, Int32 count, AsyncProtocolRequest asyncRequest)
   at System.Net.Security._SslStream.ReadHeaderCallback(AsyncProtocolRequest asyncRequest)
   at System.Net.AsyncProtocolRequest.CompleteRequest(Int32 result)
   at System.Net.FixedSizeReader.CheckCompletionBeforeNextRead(Int32 bytes)
   at System.Net.FixedSizeReader.ReadCallback(IAsyncResult transportResult)
   at System.Net.LazyAsyncResult.Complete(IntPtr userToken)
   at System.Net.ContextAwareResult.CompleteCallback(Object state)
   at System.Threading.ExecutionContext.RunInternal(ExecutionContext executionContext, ContextCallback callback, Object state, Boolean preserveSyncCtx)
   at System.Threading.ExecutionContext.Run(ExecutionContext executionContext, ContextCallback callback, Object state, Boolean preserveSyncCtx)
   at System.Threading.ExecutionContext.Run(ExecutionContext executionContext, ContextCallback callback, Object state)
   at System.Net.ContextAwareResult.Complete(IntPtr userToken)
   at System.Net.LazyAsyncResult.ProtectedInvokeCallback(Object result, IntPtr userToken)
   at System.Net.Sockets.BaseOverlappedAsyncResult.CompletionPortCallback(UInt32 errorCode, UInt32 numBytes, NativeOverlapped* nativeOverlapped)
   at System.Threading._IOCompletionCallback.PerformIOCompletionCallback(UInt32 errorCode, UInt32 numBytes, NativeOverlapped* pOVERLAP) stack trace    at System.Reactive.PlatformServices.ExceptionServicesImpl.Rethrow(Exception exception)
   at System.Reactive.Stubs.<>c.<.cctor>b__2_1(Exception ex)
   at System.Reactive.AnonymousSafeObserver`1.OnError(Exception error)
   at System.Reactive.Linq.ObservableImpl.Merge`1._.Iter.OnError(Exception error)
   at System.Reactive.Linq.ObservableImpl.SelectMany`2._.Iter.OnError(Exception error)
   at System.Reactive.Linq.ObservableImpl.Throw`1._.Invoke()
   at System.Reactive.Concurrency.Scheduler.Invoke(IScheduler scheduler, Action action)
   at System.Reactive.Concurrency.ImmediateScheduler.Schedule[TState](TState state, Func`3 action)
   at System.Reactive.Concurrency.Scheduler.Schedule(IScheduler scheduler, Action action)
   at System.Reactive.Linq.ObservableImpl.Throw`1._.Run()
   at System.Reactive.Linq.ObservableImpl.Throw`1.Run(IObserver`1 observer, IDisposable cancel, Action`1 setSink)
   at System.Reactive.Producer`1.Run(IScheduler _, State x)
   at System.Reactive.Concurrency.ScheduledItem`2.InvokeCore()
   at System.Reactive.Concurrency.CurrentThreadScheduler.Trampoline.Run(SchedulerQueue`1 queue)
   at System.Reactive.Concurrency.CurrentThreadScheduler.Schedule[TState](TState state, TimeSpan dueTime, Func`3 action)
   at System.Reactive.Concurrency.LocalScheduler.Schedule[TState](TState state, Func`3 action)
   at System.Reactive.Producer`1.SubscribeRaw(IObserver`1 observer, Boolean enableSafeguard)
   at System.ObservableExtensions.SubscribeSafe[T](IObservable`1 source, IObserver`1 observer)
   at System.Reactive.Linq.ObservableImpl.SelectMany`2._.SubscribeInner(IObservable`1 inner)
   at System.Reactive.Linq.ObservableImpl.SelectMany`2._.OnNext(TSource value)
   at System.Reactive.Subjects.Subject`1.OnNext(T value)
   at System.Reactive.Linq.ObservableImpl.FromEventPattern.Impl`2.<>c__DisplayClass3_0.<GetHandler>b__1(Object sender, TEventArgs eventArgs)
   at System.EventHandler`1.Invoke(Object sender, TEventArgs e)
   at WampSharp.V2.Client.WampSessionClient`1.OnConnectionBroken(WampSessionCloseEventArgs e)
   at WampSharp.V2.Client.WampSessionClient`1.RaiseConnectionBroken()
   at WampSharp.V2.Client.WampSessionClient`1.OnConnectionClosed()
   at WampSharp.V2.Client.WampChannel`1.OnConnectionClosed(Object sender, EventArgs e)
   at WampSharp.Core.Listener.ReviveClientConnection`1.RaiseConnectionClosed()
   at WampSharp.Core.Listener.ReviveClientConnection`1.OnConnectionClosed(Object sender, EventArgs e)
   at WampSharp.WebSocket4Net.WebSocket4NetConnection`1.RaiseConnectionClosed()
   at WampSharp.WebSocket4Net.WebSocket4NetConnection`1.WebSocketOnClosed(Object sender, EventArgs eventArgs)
   at WebSocket4Net.WebSocket.FireClosed()
   at WebSocket4Net.WebSocket.OnClosed()
   at WebSocket4Net.WebSocket.client_Closed(Object sender, EventArgs e)
   at SuperSocket.ClientEngine.ClientSession.OnClosed()
   at SuperSocket.ClientEngine.SslStreamTcpSession.OnDataRead(IAsyncResult result)
   at System.Net.LazyAsyncResult.Complete(IntPtr userToken)
   at System.Net.LazyAsyncResult.ProtectedInvokeCallback(Object result, IntPtr userToken)
   at System.Net.Security._SslStream.StartFrameBody(Int32 readBytes, Byte[] buffer, Int32 offset, Int32 count, AsyncProtocolRequest asyncRequest)
   at System.Net.Security._SslStream.ReadHeaderCallback(AsyncProtocolRequest asyncRequest)
   at System.Net.AsyncProtocolRequest.CompleteRequest(Int32 result)
   at System.Net.FixedSizeReader.CheckCompletionBeforeNextRead(Int32 bytes)
   at System.Net.FixedSizeReader.ReadCallback(IAsyncResult transportResult)
   at System.Net.LazyAsyncResult.Complete(IntPtr userToken)
   at System.Net.ContextAwareResult.CompleteCallback(Object state)
   at System.Threading.ExecutionContext.RunInternal(ExecutionContext executionContext, ContextCallback callback, Object state, Boolean preserveSyncCtx)
   at System.Threading.ExecutionContext.Run(ExecutionContext executionContext, ContextCallback callback, Object state, Boolean preserveSyncCtx)
   at System.Threading.ExecutionContext.Run(ExecutionContext executionContext, ContextCallback callback, Object state)
   at System.Net.ContextAwareResult.Complete(IntPtr userToken)
   at System.Net.LazyAsyncResult.ProtectedInvokeCallback(Object result, IntPtr userToken)
   at System.Net.Sockets.BaseOverlappedAsyncResult.CompletionPortCallback(UInt32 errorCode, UInt32 numBytes, NativeOverlapped* nativeOverlapped)
   at System.Threading._IOCompletionCallback.PerformIOCompletionCallback(UInt32 errorCode, UInt32 numBytes, NativeOverlapped* pOVERLAP) Connection got broken. CloseType:Disconnection

**Comment by darkl** [comment]
In order to prevent this exception, please provide an OnError handler to the IObservable Subscribe extension method.

**Comment by seba-0** [comment]
Thanks, I missed that overload. Might me good idea to add it as an example in documentation pages.

**Comment by seba-0** [comment]
I had an old dll when i closed issue. Can you give mi a hint what am I missing here:
var factory = new DefaultWampChannelFactory();
var channel = factory.CreateJsonChannel(Settings.Url, "realm1");
var realmProxy = channel.RealmProxy;
 Func<Task> conTask = async () =>
{
  await channel.Open();
  var subject = realmProxy.Services.GetSubject(ins);
  var subscription = subject.Subscribe(y => HandleMessage(y), er => LogEx(er));
}
WampChannelReconnector reconnector = new WampChannelReconnector(channel, () =>
{
    conTask();
    return null;
});

reconnector.Start();

**Comment by darkl** [comment]
Don't know if it will make a difference, but you should return the Open
task from your Func.

Elad

**Comment by seba-0** [comment]
Hi,
Thaks for taking time to check this issue I'm having. I changed reconnector line to
WampChannelReconnector reconnector = new WampChannelReconnector(channel, () =>
{
  return conTask();
});

but this doesn't help also. Only fix that works for me is wrapping callback call in OnConnectionError method of WampSessionClient.

**Comment by darkl** [comment]
Please write full instructions to reproduce this issue and I'll try to
check it during the week.

Elad

**Comment by seba-0** [comment]
Hi, here is the project that can lead to unhandled exception. All code is in program.cs. You would also need TCPView tool free download form https://technet.microsoft.com/en-us/sysinternals/tcpview.aspx. Steps to reproduce problem:
1. Start sample in debugger
2. Start TCPView and located debuged exe (it should be wampclient.vshost.exe) in tools window
3. In TCPView right click on exe and select close connection
4. Debugger will report unhandled exception and continuing will crash application

[WampClient.zip](https://github.com/Code-Sharp/WampSharp/files/1037447/WampClient.zip)

**Comment by darkl** [comment]
You haven't added an OnError handler to the ticker subscription.

Elad

**Comment by seba-0** [comment]
You are right! Thank you for your help. First time I tired your suggestion I commented out first subscription and forgot to add OnError to it. That is the reason I closed issue at first and then reopened it.

One again thanks for help.
