### ISSUE TITLE
JTokenMessageParser.Parse: Failed parsing message

### ISSUE THREAD

**Issue by drweeto** [Code-Sharp/WampSharp#206]
The following error was logged upon attempting to open up a connection to Bitfinex's websocket service:

2017-08-04 10:30:18,195 [16] ERROR [LoggerExecutionWrapper.Log(0)] - Failed parsing message {"event":"info","version":2}
System.ArgumentNullException: Value cannot be null.
Parameter name: source
   at System.Linq.Enumerable.Skip[TSource](IEnumerable`1 source, Int32 count)
   at WampSharp.Newtonsoft.JsonWampMessageFormatter.Parse(JToken message)
   at WampSharp.Newtonsoft.JTokenMessageParser.Parse(String text)

I upgraded to 1.2.5.40-beta version of WampSharp and 10.0.3 of Newtonsoft.Json to see if it made a difference, without luck, 

Let me know if there is any more information I can provide.

**Comment by darkl** [comment]
The message isn't a proper WAMP message. It isn't even an array. WampSharp
is a library for the WAMP protocol, not for an arbitrary WebSocket
subprotocol.

Elad

**Comment by drweeto** [comment]
Thank you very much for clearing that up for me.
