### ISSUE TITLE
System.Net.Http.WinHttpException: The connection with the server was terminated abnormally

### ISSUE THREAD

**Issue by petrovalex** [Code-Sharp/WampSharp#208]
Hello,

I am hosting both client and WampHost in ASP.NET Core application. Was trying to use WampChannelReconnector to enable reconnection, but when I stop my WampHost application reconnection not always happening. Sometimes it is happening, but as I stop/start my host at some point it stops, or might not be triggered even once.

From the logs I am getting this error in my client application:

RequestPath /connect
SourceContext WampSharp.WebSockets.ControlledTextWebSocketConnection`1[[Newtonsoft.Json.Linq.JToken, Newtonsoft.Json, Version=10.0.0.0, Culture=neutral, PublicKeyToken=30ad4fe6b2a6aeed]]
System.Net.Http.WinHttpException: The connection with the server was terminated abnormally
   at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at System.Net.WebSockets.WinHttpWebSocket.<ReceiveAsync>d__27.MoveNext()
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at WampSharp.WebSockets.WebSocketWrapperConnection`1.<ReadMessage>d__16.MoveNext()
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at WampSharp.WebSockets.WebSocketWrapperConnection`1.<RunAsync>d__14.MoveNext()

**Comment by darkl** [comment]
I think that this error is irrelevant, as it is actually caught and [raises the ConnectionClosed handler](https://github.com/Code-Sharp/WampSharp/blob/2bee21bbd5f6441f33a73cdd3a0a08469adaf685/src/net45/Extensions/WampSharp.WebSockets/WebSockets/WebSocketWrapperConnection.cs#L127).

Can you create a simple client/router sample that easily reproduces this?

Elad

**Comment by petrovalex** [comment]
Current observation is that the issue replicates quite consistently when I start another client (Client B, .net core console app), which registers rpc operation in RpcCatalog with RegisterOptions { Invoke = "single"} and additionally publishes heartbeat through Services, which Client A (asp.net core app) subscribed to. After stopping WampHost, ConnectionBroken event is not fired in Client A and reconnection is not triggered. Client B works as expected. 

Will try to isolate that in sample project.

**Comment by petrovalex** [comment]
Here is sample project:
https://bitbucket.org/alexpetrov/wampsharp-208

Was able to reproduce with 1 client only (client_a), so I first start broker, then client_a, then stop broker.
connect function is not called in client_a. If I comment out this part:

`channel.RealmProxy.Services.GetSubject("status").Subscribe(_ =>
					 {
						 Console.WriteLine("On status");
					 });`
then it works.
I am booting those sites in IIS Express on Windows 10 machine.

**Comment by darkl** [comment]
Thanks. I'll try to investigate it in the next few days.

Elad

**Comment by darkl** [comment]
Can you try specifying a OnError handler for the Subscribe method?

Elad

**Comment by petrovalex** [comment]
Thanks for reply. OnError handler looks like fixing the sample, reconnection is happening.
Is it a bug or onError should be always provided?

**Comment by darkl** [comment]
Should be provided, otherwise an error will result with an unhandled
exception.

Elad

**Comment by darkl** [comment]
I'm leaving this open, as documentation should be updated so that its samples use the OnError overload.

**Comment by petrovalex** [comment]
OK, and my application code still does not work properly. OnError is actully not called there, still checking

**Comment by darkl** [comment]
I'd suggest you to subscribe to AppDomain.CurrentDomain.UnhandledException.

Elad
