### ISSUE TITLE
Not connecting WAMP-CRA

### ISSUE THREAD

**Issue by kitkat14** [Code-Sharp/WampSharp#230]
Hi

First of all excuse my noob-ness. I am not that good at C#.

I am trying to connect to an API but I am not getting it to work for days

```
var wampConnection = null;
var wampSession = null;
var wampUser = 'web';
var wampPassword = 'web';
```
	
	function onChallenge(wampSession, method, extra) {
		if (method == 'wampcra') {
			return autobahn.auth_cra.sign(wampPassword, extra.challenge);
		}
	};
	
	function connectionOpen(session, details) {
		wampSession.call('f_all_miner_updates', ['0a7a6fade943f7b6b9e96b4d1516bfcc733b5158af18d1b43aeec7e45a238c02']).then(initialSessionUpdatesReceived);
	};
	
	function initialSessionUpdatesReceived(updates) {   
	    //After handling the initial information, now subscribe to receive future updates.	    
	    wampSession.subscribe('miner_updates_0a7a6fade943f7b6b9e96b4d1516bfcc733b5158af18d1b43aeec7e45a238c02', onMinerUpdate);
	};
	
	function onMinerUpdate(update) {
	    //Handle live miner updates here.
	};
    
	wampConnection = new autobahn.Connection({
		url : 'wss://live.prohashing.com:443/ws',
		realm : 'mining',
		authmethods: ['wampcra'],
		authid: wampUser,
		onchallenge: onChallenge
	});
	
	wampConnection.onopen = connectionOpen;
	wampConnection.open();
				
```
**I am trying to mimick the same into C#**
```
      class Program
      {
        static void Main(string[] args)
        {
            DefaultWampChannelFactory factory = new DefaultWampChannelFactory();
            IWampClientAuthenticator authenticator = new WampCraClientAuthenticator(authenticationId: "web", secret: "web");

            IWampChannel channel = factory.CreateJsonChannel("wss://live.prohashing.com:443/ws", "mining", authenticator);
            IWampRealmProxy realmProxy = channel.RealmProxy;

            channel.RealmProxy.Monitor.ConnectionEstablished +=
    (sender, arg) =>
    {
        Console.WriteLine("connected session with ID " + arg.SessionId);

        dynamic details = arg.WelcomeDetails.OriginalValue.Deserialize<dynamic>();

        Console.WriteLine("authenticated using method '{0}' and provider '{1}'", details.authmethod,
                          details.authprovider);

        Console.WriteLine("authenticated with authid '{0}' and authrole '{1}'", details.authid,
                          details.authrole);
    };

            channel.RealmProxy.Monitor.ConnectionBroken += (sender, arg) =>
            {
                dynamic details = arg.Details.OriginalValue.Deserialize<dynamic>();
                Console.WriteLine("disconnected " + arg.Reason + " " + details.reason + details);
            };

            channel.Open().ConfigureAwait(false);

            Console.ReadLine();
        }
    }
```


But I get a connection disconnected every time..

**Comment by darkl** [comment]
Your sample works fine on my computer.
![image](https://user-images.githubusercontent.com/1126390/34952236-0f3b10a8-f9e7-11e7-9233-23796fc39c6f.png)

**Comment by kitkat14** [comment]
I was behind a proxy... 

these two parts: 


function connectionOpen(session, details) {
	wampSession.call('f_all_miner_updates', ['0a7a6fade943f7b6b9e96b4d1516bfcc733b5158af18d1b43aeec7e45a238c02']).then(initialSessionUpdatesReceived);
};

function initialSessionUpdatesReceived(updates) {   
    //After handling the initial information, now subscribe to receive future updates.	    
    wampSession.subscribe('miner_updates_0a7a6fade943f7b6b9e96b4d1516bfcc733b5158af18d1b43aeec7e45a238c02', onMinerUpdate);
};


how would that translate ?

**Comment by darkl** [comment]
```csharp
public interface IMinerUpdatesProxy
{
    [WampProcedure("f_all_miner_updates")]
    Task AllMinerUpdatesAsync(string id);
}
```

```csharp
IMinerUpdatesProxy proxy = channel.RealmProxy.Services.GetCalleeProxy<IMinerUpdatesProxy>();

await proxy.AllMinerUpdatesAsync("0a7a6fade943f7b6b9e96b4d1516bfcc733b5158af18d1b43aeec7e45a238c02");

IWampSubject subject = channel.RealmProxy.Services.GetSubject(
    "miner_updates_0a7a6fade943f7b6b9e96b4d1516bfcc733b5158af18d1b43aeec7e45a238c02");

subject.Subscribe(x =>
{

});
```

**Comment by kitkat14** [comment]
@darkl Thanks 👍  it works I will try to import it in Xamarin but I have already seen you can't import WampSharp to the PCL. Known issue ?

**Comment by darkl** [comment]
WampSharp supports netstandard2.0 and therefore to my understanding should work on Xamarin.

Elad

**Comment by kitkat14** [comment]
@darkl I will try to change it to .net 2.0. Do I need to add the package to each project or is it enough to have it added to the shared project ?

**Comment by kitkat14** [comment]
@darkl  I have added the Wampsharp.Default to the shared project that runs netstandard 2.0 
![snip20180117_1](https://user-images.githubusercontent.com/7466866/35066842-4965e19e-fbd2-11e7-99b3-f4ecf5c75996.png)

![snip20180117_2](https://user-images.githubusercontent.com/7466866/35066999-c3d9ebf0-fbd2-11e7-8976-05eacb282d93.png)

I am getting the following error when trying to run it with a class file 

_/Users/admin/Projects/App/iOS/MTOUCH: Error MT2002: Failed to resolve "WampSharp.V2.Realm.WampSessionCreatedEventArgs" reference from "WampSharp, Version=1.0.0.0, Culture=neutral, PublicKeyToken=null" (MT2002) (App.iOS)_

**Comment by yohsk10** [comment]
Hi,

I tried to use WampSharp in Xarmarin.Forms application and it works fine. What I did is download the version 15.5, when you create a new Xamarin.Forms project you have a template with NetStandard instead of PCL. It is much better when you start because with PCL library you must install the WampSharp.Default.Client in the Xamarin.Android/iOS project too if I remember right.

What you can do is to put this line in your iOS application BuildEvents :

`xcopy /y "$(SolutionDir)Path\to\your\PCL\bin\folder\*.dll" "$(SolutionDir)Path\to\your\iOS\output\folder"`

It will copy the dll present in your PCL application and put it into your iOS output folder

**Comment by kitkat14** [comment]
@yohsk10 

I am now trying for 2 days to just get the project to build.
Do you have basic solution that is working ? I  mean a .netshared 2.0 project with the packages added to the shared project and the Android or iOS project.

What ever I try I am getting other errors because of packages. I need to know exactly which package to add where...

- Shared
WampSharp.Default

- iOS/Android
WampSharp.Default
WampSharp.Default.Client

I tried all kind of combinations and get different kind of errors. The last one I get now is this


_Can't resolve the reference 'System.Void WampSharp.V2.Client.WampCraClientAuthenticator::.ctor(System.String,System.String,System.String,System.Nullable`1<System.Int32>,System.Nullable`1<System.Int32>)', referenced from the method 'System.Void App.Page/<refreshAsync>d__9::MoveNext()' in 'WampSharp, Version=1.0.0.0, Culture=neutral, PublicKeyToken=null'. (MT2101) (Prohashing.iOS)_

These are the only lines that I have in the project that create enough problems (it doesnt even complete the build)

			```
    DefaultWampChannelFactory factory = new DefaultWampChannelFactory();
     IWampClientAuthenticator authenticator = new WampCraClientAuthenticator(authenticationId: "web", secret: "web");
     IWampChannel channel = factory.CreateJsonChannel("wss://live.prohashing.com:443/ws", "mining", authenticator);
     IWampRealmProxy realmProxy = channel.RealmProxy;
```

**Comment by yohsk10** [comment]
The only project who has the libraries is my shared project in netstandard 2.0. I have not installed anything in the other projects (iOS and Android).

I have this project who works great. You must change the IP address in the XamarinWamp.ViewModel.MainViewModel file (be carefull, do not use the localhost address)

[TestXamarinWamp.zip](https://github.com/Code-Sharp/WampSharp/files/1651783/TestXamarinWamp.zip)

Here you have the project who published the data :

[PublisherWamp.zip](https://github.com/Code-Sharp/WampSharp/files/1651786/PublisherWamp.zip)

Best regards
Yohsk

**Comment by kitkat14** [comment]
@yohsk10 

I am trying for days I cant get it to work when I try to add the authenticator. Also I need to add the projects to the sub projects in order to work or else it doesnt want to build (because it doesnt have the reference)

Even then I am getting the following issue only if i remove the authenticator it will build. I think I will give up


Error MT2101: Can't resolve the reference 'System.Void WampSharp.V2.Client.WampCraClientAuthenticator::.ctor(System.String,System.String,System.String,System.Nullable`1<System.Int32>,System.Nullable`1<System.Int32>)', referenced from the method 'System.Void App.Page::refreshMinersAsync()' in 'WampSharp, Version=1.0.0.0, Culture=neutral, PublicKeyToken=null'. (MT2101) (Prohashing.iOS)

**Comment by darkl** [comment]
I have an idea what can cause the issue. There exists a folder Xamarin.iOS10 in WampSharp.nuspec which contains PCL dlls. These dlls don't have WampCra as it is not present in PCL.
Perhaps the existence of Xamarin.iOS10 folder makes the IDE ignore the netstandard2.0 folder? Can you check if the referenced dlls are from the Xamarin.iOS10 folder?

Elad

**Comment by darkl** [comment]
Also what IDE are you using? What version?

**Comment by darkl** [comment]
I just released WampSharp v1.2.7.48-beta to NuGet gallery. This NuGet package does not contain a Xamarin.iOS10 folder. Please make sure you are using the latest Visual Studio 2017 update. Hopefully now the IDE will recognize the WampCraClientAuthenticator class. Also, hopefully this doesn't break anything.

Elad

**Comment by kitkat14** [comment]
@darkl thanks for taking the time to finding out the issue. Unfortunatly I get exactly the same issue. If you have Visual Studio 2015 and Xamarin I can forward you the project but I think its quite easy to create the same project because its only a couple lines of code.

**Comment by darkl** [comment]
Please try with the latest Visual Studio 2017 version.

Elad

**Comment by kitkat14** [comment]
@darkl I dont know why I wrote 2015 but I am using 2017 (created the application also with 2017)

**Comment by darkl** [comment]
Please attach your complete non-working example.

Elad

**Comment by darkl** [comment]
Please try v1.2.7.49-beta. Hopefully, this should work.

**Comment by darkl** [comment]
Closing due to inactivity.

**Comment by raineycd** [comment]
I am not able to connect using the code sample - can you check if it still works please?

`using System;
using System.Collections.Generic;
using System.Linq;
using System.Text;
using System.Threading.Tasks;
using WampSharp.V2;
using WampSharp.V2.Client;

namespace ProhashingWamp
{
    class Program
    {
        static void Main(string[] args)
        {
            DefaultWampChannelFactory factory = new DefaultWampChannelFactory();
            IWampClientAuthenticator authenticator = new WampCraClientAuthenticator(authenticationId: "web", secret: "web");

            IWampChannel channel = factory.CreateJsonChannel("wss://live.prohashing.com:444/ws", "mining", authenticator);
            
            IWampRealmProxy realmProxy = channel.RealmProxy;

            channel.RealmProxy.Monitor.ConnectionEstablished += (sender, arg) =>
            {
                Console.WriteLine("connected session with ID " + arg.SessionId);

                dynamic details = arg.WelcomeDetails.OriginalValue.Deserialize<dynamic>();

                Console.WriteLine("authenticated using method '{0}' and provider '{1}'", details.authmethod,
                                  details.authprovider);

                Console.WriteLine("authenticated with authid '{0}' and authrole '{1}'", details.authid,
                                  details.authrole);
            };

            channel.RealmProxy.Monitor.ConnectionBroken += (sender, arg) =>
            {
                //dynamic details = arg.Details.OriginalValue.Deserialize<dynamic>();
                //Console.WriteLine("disconnected " + arg.Reason + " " + details.reason + details);
                Console.WriteLine("disconnected " + arg.Reason);
            };

            Func<Task> connect = async () =>
            {
                Console.WriteLine("opening");

                await channel.Open().ConfigureAwait(false);

            };

            connect();

            Console.ReadLine();
        }
    }
}`

**Comment by raineycd** [comment]
It just sits and disconnects - no messages/errors.  If I put in  wss://api.poloniex.com without any authentication (they dont use any) it connects and echos out the session , etc.

**Comment by StevenBonePgh** [comment]
[Polinex no longer uses WAMP](https://github.com/Code-Sharp/PoloniexWebSocketsApi) so that is not a good example.  I am asking for Debug log messages.  If you configure a logging framework in Main() and set it to log Debug level, that is what I'm looking for (essentially what is going across the wire and internal to WampSharp).  WampSharp uses [liblog](https://github.com/damianh/LibLog/wiki)for logging, so log4net, nlog, etc. is supported automatically.  See also [here](https://github.com/Code-Sharp/WampSharp/blob/v18.5.1/src/net45/WampSharp/App_Packages/LibLog.4.2/LibLog.cs).

**Comment by darkl** [comment]
This is some issue with WebSocket4Net. I get the exception
`
Unhandled Exception: System.Security.Authentication.AuthenticationException: A call to SSPI failed, see inner exception. ---> System.ComponentModel.Win32Exception: The function requested is not supported
   --- End of inner exception stack trace ---
   at System.Net.Security.SslState.InternalEndProcessAuthentication(LazyAsyncResult lazyResult)
   at System.Net.Security.SslState.EndProcessAuthentication(IAsyncResult result)
   at System.Net.Security.SslStream.EndAuthenticateAsClient(IAsyncResult asyncResult)
   at SuperSocket.ClientEngine.SslStreamTcpSession.OnAuthenticated(IAsyncResult result)
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at System.Runtime.CompilerServices.ConfiguredTaskAwaitable.ConfiguredTaskAwaiter.GetResult()
   at ProhashingWamp.Program.<Main>d__0.MoveNext() in C:\Users\Elad Zelingher\source\repos\ConsoleApp8\ConsoleApp2\Program.cs:line 45
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at System.Runtime.CompilerServices.TaskAwaiter.GetResult()
   at ProhashingWamp.Program.<Main>(String[] args)
`

Replacing to WampSharp.WebSockets and using [this code](https://gist.github.com/darkl/4464b45ca6bd7161aaaa7c3de6dda468) works fine.

Elad

**Comment by StevenBonePgh** [comment]
The "A call to SSPI failed" "The function requested is not supported" exceptions are caused by the inability to negotiate a suitable SSL security level between client and server.  My guess is that you are running this under .NET 4.5.x or lower, as .NET 4.6 enables the higher security protocols by default, AND that the prohashing.com webserver has disabled support for old protocols (as most have these days). You'd need to explicitly opt in to supporting higher TLS levels when constructing it.  See #158 and #170.

I could possibly be wrong on assuming that WebSocket4Net defaults to using the value(s) contained in `ServicePointManager.SecurityProtocol` by default.  If you compile/run your test harness under .NET 4.6+ does it work?

**Comment by raineycd** [comment]
Yep it's using .NET 4.6.1

I suspect Prohashing has a free cert that is lame. I just have seen same code work a couple months ago so they may have changed the cert to one that will not be valid.  I wish they just kept the REST api working, I just need to grab the current estimate of profit.  Lots of work now dealing with WAMP to get that.  I may look at some screen scraping, but they use dynamic on their site.  Just frustrated that this should have been a 30 minute project and I am 5 hours into it and can't even connect. lol

**Comment by darkl** [comment]
I tried the code over .NET Framework 4.6.1 and this error occurs.
Interestingly, over .NET Core 2.0, the WebSocket4Net version works.

Elad

**Comment by darkl** [comment]
@raineycd I provided you a solution: install WampSharp.WebSockets and WampSharp.NewtonsoftJson instead of WampSharp.Default.Client and use my [gist](https://gist.github.com/darkl/4464b45ca6bd7161aaaa7c3de6dda468).

**Comment by darkl** [comment]
Uninstall WampSharp.WebSocket4Net and install WampSharp.WebSockets instead.
You might also get errors since I use C# 7.1 features. In this case, rename
the Main to a different method and call from the classic private static
void Main method.

Elad

**Comment by raineycd** [comment]
Now we are making progress!  Thank you so much!  Now I am going to try to get the data I need and write it to my MYSQL db!

**Comment by raineycd** [comment]
Elad, would it be possible to pay you to code this for me? :-)  Just need subscription and get a few data points returned into variables when they update.  I have done the MYSQL parts before, I am just in way over my head on this WAMP stuff.

**Comment by darkl** [comment]
[Here](https://gist.github.com/darkl/9b1c2ea43e8af882c6c6c5659a0ea336) is an example that does more or less the same thing [this example](https://prohashing.com/help.html) does (For some reason the onMinerUpdate event handler does get events).

I generated the BlockUpdate class using [this site](http://json2csharp.com) (I initially received used an object for the foundBlockUpdates Subject, and then copied and pasted its ToString to the json2csharp site). You are always welcome to give a donation via the link in the GitHub README.

Elad

**Comment by raineycd** [comment]
Wow thanks!  You are a pure genius!  Hope you get paid very very well!  I am just a script hack lol

I will def be donating!  I think I can work with this last example!  I appreciate it!!!!!

**Comment by raineycd** [comment]
@darkl 

Ok, so when I echo out x from the subject.Subscribe, I get this WampSharp.V2.WampSerializedEvent`1[Newtonsoft.Json.Linq.JToken]

I think the WAMP subject is returning an array, but no clue how to get the data out of it.

using System;
using System.Threading.Tasks;
using WampSharp.V2;
using WampSharp.V2.Client;
using WampSharp.V2.Fluent;
using WampSharp.V2.Rpc;
using System.Net;
using System.Reactive.Subjects;
using Newtonsoft.Json;

namespace ProhashingWamp
{
    class Program
    {
        static void Main(string[] args)
        {
            Run(args);
            Console.ReadLine();
        }

        static async Task Run(string[] args)
        {
            ServicePointManager.SecurityProtocol = SecurityProtocolType.Tls12;

            WampChannelFactory factory = new WampChannelFactory();

            IWampChannel channel = factory.ConnectToRealm("mining")
                                          .WebSocketTransport(new Uri("wss://live.prohashing.com:443/ws"))
                                          .JsonSerialization()
                                          .CraAuthentication("web", "web")
                                          .Build();

            IWampRealmProxy realmProxy = channel.RealmProxy;

            channel.RealmProxy.Monitor.ConnectionEstablished +=
                (sender, arg) =>
                {
                    Console.WriteLine("connected session with ID " + arg.SessionId);

                    dynamic details = arg.WelcomeDetails.OriginalValue.Deserialize<dynamic>();

                    Console.WriteLine("authenticated using method '{0}' and provider '{1}'", details.authmethod,
                                      details.authprovider);

                    Console.WriteLine("authenticated with authid '{0}' and authrole '{1}'", details.authid,
                                      details.authrole);
                };

            channel.RealmProxy.Monitor.ConnectionBroken +=
                (sender, arg) =>
                {
                    dynamic details = arg.Details.OriginalValue.Deserialize<dynamic>();
                    Console.WriteLine("disconnected " + arg.Reason + " " + details.reason + details);
                    Console.WriteLine("disconnected " + arg.Reason);
                };

            await channel.Open().ConfigureAwait(false);

            IMinerUpdatesProxy proxy = channel.RealmProxy.Services.GetCalleeProxy<IMinerUpdatesProxy>();

            //await proxy.AllMinerUpdatesAsync("0a7a6fade943f7b6b9e96b4d1516bfcc733b5158af18d1b43aeec7e45a238c02");

            ISubject<BlockUpdate> foundBlockUpdates =
                channel.RealmProxy.Services.GetSubject<BlockUpdate>("profitability_updates");

            foundBlockUpdates.Subscribe(blockUpdate =>
            {
                // Handle found blocks here.
                //Console.WriteLine("CoinbaseValue: " + blockUpdate.VarUSD);
            });

            IWampSubject subject = channel.RealmProxy.Services.GetSubject("profitability_updates");


            subject.Subscribe(x =>
            {
                string deets = x.ToString();
                Console.WriteLine(deets);

            });

            await Task.Yield();
        }
    }

    public interface IMinerUpdatesProxy
    {
        [WampProcedure("f_all_profitability_updates")]
        Task<object> AllMinerUpdatesAsync(string id);
    }

    public class BlockUpdate
    {
        [JsonProperty("usd")]
        public object[] VarUSD { get; set; }


        [JsonProperty("data_timestamp")]
        public double DataTimestamp { get; set; }
    }
}
