### ISSUE TITLE
System.Security.Authentication.AuthenticationException on channel.Open

### ISSUE THREAD

**Issue by ifoatov** [Code-Sharp/WampSharp#233]
Hi, I get error when try to open channel

`var channelFactory = new DefaultWampChannelFactory();`
 `var channel = channelFactory.CreateMsgpackChannel("wss://api.poloniex.com", "realm1");`
` await channel.Open();`

System.Security.Authentication.AuthenticationException
  HResult=0x80131501
  Message= a call to sspi failed, see inner exception.
  Source=System
  StackTrace:
   at System.Net.Security.SslState.InternalEndProcessAuthentication(LazyAsyncResult lazyResult)
   at System.Net.Security.SslState.EndProcessAuthentication(IAsyncResult result)
   at System.Net.Security.SslStream.EndAuthenticateAsClient(IAsyncResult asyncResult)
   at SuperSocket.ClientEngine.SslStreamTcpSession.OnAuthenticated(IAsyncResult result)
   at System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at System.Runtime.CompilerServices.TaskAwaiter.GetResult()
   at wpfTerminal.ViewModels.MainViewModel.<StartSomething>d__4.MoveNext() in D:\Git\cmTrading\wpfTerminal\ViewModels\MainViewModel.cs:line 37

Inner Exception 1:
Win32Exception: Function not supported

**Comment by darkl** [comment]
If this is Poloniex related, please see my comment for #232.

**Comment by darkl** [comment]
See also #234.
