### ISSUE TITLE
After an Unregister Procedure Failure, await RPC call never returns

### ISSUE THREAD

**Issue by StevenBonePgh** [Code-Sharp/WampSharp#260]
I have a client on one process and a client in another process using WebSocket transport. Using the reconnector, when a connection happens on the client, I register a couple of callee endpoints (using `WampInvokePolicy.Last` because the client can reconnect prior to the router detecting the previous disconnect).  When registering, I keep the `Task<IAsyncDisposable>` around so I can dispose them when we gracefully close the connection to unregister.  Through a quirk of implementation, when the router is restarted and the client reconnects my code disposes the `Task<IAsyncDisposable>` from the prior connection AFTER re-registering.  This results in the following error on the router:

> Failed unregistering procedure with registration id 489500151141588. Unregistration request id: 697161578502379  [L:WampSharp.V2.Rpc.WampRpcServer`1[[Newtonsoft.Json.Linq.JToken, Newtonsoft.Json, Version=11.0.0.0, Culture=neutral, PublicKeyToken=30ad4fe6b2a6aeed]]] [S:(null)] [U:(null)] [R:(null)] WampSharp.V2.Core.Contracts.WampException: Error uri: 'wamp.error.no_such_registration', details: registrationId: 489500151141588
>    at WampSharp.V2.Rpc.WampCalleeOperationCatalog`1.Unregister(IWampCallee callee, Int64 registrationId) in D:\a\1\s\src\net45\WampSharp\WAMP2\V2\Rpc\Dealer\WampCalleeOperationCatalog.cs:line 71
>    at WampSharp.V2.Rpc.WampRpcServer`1.Unregister(IWampCallee callee, Int64 requestId, Int64 registrationId) in D:\a\1\s\src\net45\WampSharp\WAMP2\V2\Rpc\Dealer\WampRpcServer.cs:line 58

After this happens, the client attempts to await an RPC call.  The call is successfully made to the desired callee, however, the await never returns.  One side is definitely in a bad state at this point.  If I remove the call to dispose the old connection's registrations it works as expected.

I assume there is some bug in WampSharp here, and what I am doing is also likely the wrong thing.  I imagine disposing the `Task<IAsyncDisposable>` is not something needed at all once the connection is dead but rather is something that should only be done prior to a graceful connection close or when removing the callee for whatever reason one may desire. I also would assume the same issue applies to subscriptions. 

What is the recommendation here?

**Comment by darkl** [comment]
Saw your edit after trying to reproduce the issue. FWIW A full working example is available [here](https://gist.github.com/darkl/0b826137e62f73661d3ac9531a8170ce).

Yeah, you should not try to dispose the AsyncDisposables after reconnecting to the router, as this resulting by sending UNREGISTER/UNSUBSCRIBE messages related to irrelevant RegistrationIds/SubscriptionIds. In an edge case, this can actually try to cause an unregistration of a different client's procedure (however, in practice this can't happen, since the router verifies the identity of the unregistering client. In the worst rare case of registration id collision, you'll unregister one of your other registered procedures of the same client).
