### ISSUE TITLE
MessageWebSocketBinaryConnection throws NotSupportedException

### ISSUE THREAD

**Issue by StevenBonePgh** [Code-Sharp/WampSharp#265]
Hi Elad, I'm not sure if you are aware, but if you use the `MessageWebSocketBinaryConnection` to attempt to use MsgPack under UWP a `NotSupportedException: Stream does not support seeking.` is thrown with a callstack of:

    at System.IO.BufferedStream.EnsureCanSeek()
    at System.IO.BufferedStream.set_Position(Int64 value)
    at WampSharp.Windows.MessageWebSocketBi naryConnection`1.<OnMessageReceived>d__2.MoveNext()

It is not a big deal for me, as I am just playing around with UWP at the moment and noticed this.

**Comment by darkl** [comment]
I think this should be solved in 18.8.5.
