### ISSUE TITLE
Closing IWampChannel on a WebSocket4Net WSS connection throws IOException

### ISSUE THREAD

**Issue by mbett7** [Code-Sharp/WampSharp#276]
When closing a channel based off a WebSocket4Net secure connection (WSS) with the IWampChannel.Close(string, GoodbyeDetails) overload it throws the following exception.
```
System.IO.IOException : Unable to write data to the transport connection: An existing connection was forcibly closed by the remote host.
  ----> System.Net.Sockets.SocketException : An existing connection was forcibly closed by the remote host
   at System.Net.Sockets.NetworkStream.BeginWrite(Byte[] buffer, Int32 offset, Int32 size, AsyncCallback callback, Object state)
   at System.Net.Security._SslStream.StartWriting(Byte[] buffer, Int32 offset, Int32 count, AsyncProtocolRequest asyncRequest)
   at System.Net.Security._SslStream.ProcessWrite(Byte[] buffer, Int32 offset, Int32 count, AsyncProtocolRequest asyncRequest)
   at System.Net.Security._SslStream.BeginWrite(Byte[] buffer, Int32 offset, Int32 count, AsyncCallback asyncCallback, Object asyncState)
   at SuperSocket.ClientEngine.AuthenticatedStreamTcpSession.SendInternal(PosList`1 items)
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at System.Runtime.CompilerServices.TaskAwaiter`1.GetResult()
   at WampTests.Tests.<HTTPS_Test>d__12.MoveNext() in C:\Git\WampTests\Tests\Tests.cs:line 282
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at NUnit.Framework.Internal.AwaitAdapter.TaskAwaitAdapter.BlockUntilCompleted() in C:\src\nunit\nunit\src\NUnitFramework\framework\Internal\AwaitAdapter.cs:line 109
   at NUnit.Framework.Internal.AsyncToSyncAdapter.Await(Func`1 invoke) in C:\src\nunit\nunit\src\NUnitFramework\framework\Internal\AsyncToSyncAdapter.cs:line 79
   at NUnit.Framework.Internal.Commands.TestMethodCommand.RunTestMethod(TestExecutionContext context) in C:\src\nunit\nunit\src\NUnitFramework\framework\Internal\Commands\TestMethodCommand.cs:line 84
--SocketException
   at System.Net.Sockets.Socket.BeginSend(Byte[] buffer, Int32 offset, Int32 size, SocketFlags socketFlags, AsyncCallback callback, Object state)
   at System.Net.Sockets.NetworkStream.BeginWrite(Byte[] buffer, Int32 offset, Int32 size, AsyncCallback callback, Object state)
```
Works without issue when using `System.Net.WebSockets` (WSS) or `WebSocket4Net` over an insecure connection (WS)

Repro:
```c#
[Test]
public async Task HTTPS_Test()
{
    ServicePointManager.ServerCertificateValidationCallback = (sender, certificate, chain, errors) => true;

    var port = 4443; //port with self-signed certificate
    var owinWebSocketTransportProvider = new OwinWebSocketTransportProvider();
    var webApp = WebApp.Start($"https://localhost:{port}/", (app) =>
    {
        owinWebSocketTransportProvider.Configure(app, "");
    });

    var transport = owinWebSocketTransportProvider.GetTransport();
    var binding = new JTokenJsonBinding();
    var realm = "some.realm";

    var router = new WampHost();
    router.RegisterTransport(transport, new[] { binding });
    router.Open();

    var factory = new DefaultWampChannelFactory();

    for (int i = 0; i < 10; i++)
    {
        var channel = factory
            .ConnectToRealm(realm)
            .WebSocketTransport($"wss://localhost:{port}/") // WebSocket4Net
            //.WebSocketTransport(new Uri($"wss://localhost:{port}/")) // System.Net.WebSockets <-- this works
            .JsonSerialization()
            .Build();

        await channel.Open();
        channel.RealmProxy.Monitor.IsConnected.ShouldBe(true);
        await channel.Close(WampErrors.CloseNormal, new GoodbyeDetails());
        channel.RealmProxy.Monitor.IsConnected.ShouldBe(false);
    }

    router.Dispose();
    webApp.Dispose();
}
```

Something strange I noticed with the above repro is that the first iteration works fine but throws on the second.

**Comment by darkl** [comment]
Sounds to me like a race condition, don't think it would be easy to fix. The problem is that the client closes the connection right after sending a GOODBYE message. This causes a race condition because we might not be able to receive the response from the router.

Elad

**Comment by mbett7** [comment]
Yeah, sounds like a race condition.  However I thought the client only closes the connection after receiving a GOODBYE message from the router following sending one?

**Comment by darkl** [comment]
I wish. In a previous version the client waited for the router to close the
connection. Apparently, that's too risky. For instance crossbario doesn't
close the connection after sending a GOODBYE message. So now we close the
connection immediately after sending a GOODBYE message. Because maybe the
router won't ever send a GOODBYE message, etc.

Elad

**Comment by mbett7** [comment]
After a bit of investigation it looks like the issue is in SuperSocket.ClientEngine.
The same exception is thrown when using a non-secure connection but is treated as the socket close event instead of an error.
