### ISSUE TITLE
InvalidOperationException from AsyncOperationCallback crashing application when using SSL

### ISSUE THREAD

**Issue by flin-zap** [Code-Sharp/WampSharp#282]
In AsyncOperationCallback, some methods are protected by a try/catch, but this particular one isn't.

Related to https://github.com/Code-Sharp/WampSharp/issues/281
It might be a good idea to review current usages of SetResult and change them to TrySetResult OR add try/catches around them?

Stacktrace:
   at System.Threading.Tasks.TaskCompletionSource`1.SetResult(TResult result)
   at WampSharp.V2.CalleeProxy.AsyncOperationCallback`1.SetResult(ResultDetails details, TResult result)
   at WampSharp.V2.CalleeProxy.AsyncOperationCallback`1.Result[TMessage](IWampFormatter`1 formatter, ResultDetails details)
   at WampSharp.V2.Client.WampCaller`1.Result(Int64 requestId, ResultDetails details)
   at WampSharp.V2.Client.WampRpcOperationCatalogProxy`1.Result(Int64 requestId, ResultDetails details)
   at WampSharp.V2.Client.WampClient`1.Result(Int64 requestId, ResultDetails details)
   at WampSharp.Core.Dispatch.Handler.WampMethodBuilder`2.<>c__DisplayClass4_0.<BuildMethod>b__0(TClient client, WampMessage`1 message)
   at WampSharp.Core.Dispatch.WampIncomingMessageHandler`2.HandleMessage(TClient client, WampMessage`1 message)
   at WampSharp.Core.Dispatch.WampIncomingMessageHandler`2.HandleMessage(WampMessage`1 message)
   at WampSharp.Core.Client.WampServerProxyHandler`1.OnMessageArrived(WampMessage`1 wampMessage)
   at WampSharp.Core.Client.WampServerProxyHandler`1.MessageArrived(Object sender, WampMessageArrivedEventArgs`1 e)
   at WampSharp.Core.Listener.ReviveClientConnection`1.RaiseMessageArrived(WampMessageArrivedEventArgs`1 e)
   at WampSharp.Core.Listener.ReviveClientConnection`1.OnMessageArrived(Object sender, WampMessageArrivedEventArgs`1 e)
   at WampSharp.WebSocket4Net.WebSocket4NetConnection`1.RaiseMessageArrived(WampMessage`1 message)
   at WampSharp.WebSocket4Net.WebSocket4NetTextConnection`1.OnMessageReceived(Object sender, MessageReceivedEventArgs e)
   at WebSocket4Net.WebSocket.FireMessageReceived(String message)
   at WebSocket4Net.Command.Text.ExecuteCommand(WebSocket session, WebSocketCommandInfo commandInfo)
   at WebSocket4Net.WebSocket.OnDataReceived(Byte[] data, Int32 offset, Int32 length)
   at WebSocket4Net.WebSocket.client_DataReceived(Object sender, DataEventArgs e)
   at SuperSocket.ClientEngine.ClientSession.OnDataReceived(Byte[] data, Int32 offset, Int32 length)
   at SuperSocket.ClientEngine.SslStreamTcpSession.OnDataRead(IAsyncResult result)
   at System.Net.LazyAsyncResult.Complete(IntPtr userToken)
   at System.Net.LazyAsyncResult.ProtectedInvokeCallback(Object result, IntPtr userToken)
   at System.Net.Security._SslStream.ProcessFrameBody(Int32 readBytes, Byte[] buffer, Int32 offset, Int32 count, AsyncProtocolRequest asyncRequest)
   at System.Net.Security._SslStream.ReadFrameCallback(AsyncProtocolRequest asyncRequest)
   at System.Net.AsyncProtocolRequest.CompleteRequest(Int32 result)
   at System.Net.FixedSizeReader.CheckCompletionBeforeNextRead(Int32 bytes)
   at System.Net.FixedSizeReader.ReadCallback(IAsyncResult transportResult)
   at System.Net.LazyAsyncResult.Complete(IntPtr userToken)
   at System.Net.ContextAwareResult.CompleteCallback(Object state)
   at System.Threading.ExecutionContext.RunInternal(ExecutionContext executionContext, ContextCallback callback, Object state, Boolean preserveSyncCtx)
   at System.Threading.ExecutionContext.Run(ExecutionContext executionContext, ContextCallback callback, Object state, Boolean preserveSyncCtx)
   at System.Threading.ExecutionContext.Run(ExecutionContext executionContext, ContextCallback callback, Object state)
   at System.Net.ContextAwareResult.Complete(IntPtr userToken)
   at System.Net.LazyAsyncResult.ProtectedInvokeCallback(Object result, IntPtr userToken)
   at System.Net.Sockets.BaseOverlappedAsyncResult.CompletionPortCallback(UInt32 errorCode, UInt32 numBytes, NativeOverlapped* nativeOverlapped)
   at System.Threading._IOCompletionCallback.PerformIOCompletionCallback(UInt32 errorCode, UInt32 numBytes, NativeOverlapped* pOVERLAP)

**Comment by darkl** [comment]
This is very disturbing. How can you explain the fact that SetResult is called twice? Can you please check your logs for the incoming WAMP messages and see if you get a RESULT message with the same request id twice?

Elad

**Comment by flin-zap** [comment]
Hi @darkl , unfortunately (or fortunately), this only happened on one particular day (3 times) while the router and the end was running version 18.10.1.2-develop. I'll reopen this if we get a more consistent repro
