### ISSUE TITLE
Error when client is killed

### ISSUE THREAD

**Issue by shanielh** [Code-Sharp/WampSharp#87]
Hi.

I get this error when one of my clients (I host a WampSharp server) is killed : 

```
2015-06-29 12:43:54,207 [37] ERROR WampSharp.Fleck.FleckWampTextConnection`1[[Ne
wtonsoft.Json.Linq.JToken, Newtonsoft.Json, Version=6.0.0.0, Culture=neutral, Pu
blicKeyToken=30ad4fe6b2a6aeed]] - A connection error occured
System.IO.IOException: Unable to read data from the transport connection: An exi
sting connection was forcibly closed by the remote host. ---> System.Net.Sockets
.SocketException: An existing connection was forcibly closed by the remote host
   at System.Net.Sockets.NetworkStream.EndRead(IAsyncResult asyncResult)
   --- End of inner exception stack trace ---
   at System.Net.Sockets.NetworkStream.EndRead(IAsyncResult asyncResult)
   at System.Threading.Tasks.TaskFactory`1.FromAsyncCoreLogic(IAsyncResult iar,
Func`2 endFunction, Action`1 endAction, Task`1 promise, Boolean requiresSynchron
ization)
```

I guess it happens because he's killed, But after I get several of those errors, Non of my published messages (from the server) is received in the client.

This is a log (from chrome) of the frames that the client receive upon connection to the server :

Client :
```
[1,"default",{"roles":{"caller":{"features":{"caller_identification":true,"progressive_call_results":true}},"callee":{"features":{"progressive_call_results":true}},"publisher":{"features":{"subscriber_blackwhite_listing":true,"publisher_exclusion":true,"publisher_identification":true}},"subscriber":{"features":{"publisher_identification":true}}}}]
```
Server :
```
[2,165570129090054,{"roles":{"dealer":{"pattern_based_registration":true,"shared_registration":true,"caller_identification":true,"progressive_call_results":true},"broker":{"features":{"publisher_identification":true,"pattern_based_subscription":true,"publisher_exclusion":true,"subscriber_blackwhite_listing":true}}}}]
```
Client :
```
[32,4760414889967616,{},"processes"]
[32,8271242154999808,{},"/processLogs"]
[32,8100974321205248,{},"processes"]
```

Server does not respond to any of those requests. This is it.

**Comment by darkl** [comment]
Do you know how to reproduce this? Do you have a minimal code snippet or
test steps that reproduce the problem? It can help.

I will be able to check this only next week, meanwhile you might want to
try the vtortola transport (see 1.2.1.6 release notes in wiki), it might
not suffer from this issue.

Elad

**Comment by shanielh** [comment]
I reproduced with creating many clients and killing them manually :-) 



—

שני.

**Comment by darkl** [comment]
Do you have a script that creates many clients? And by killing them
manually you mean by using task manager?

You might also try to enable logs (they are written using LibLog with
WampSharp. prefix) and see if there is something interesting there.

Elad

**Comment by darkl** [comment]
Hi,
I've been working on this, and it should work fine in v1.2.2.9-beta.

Thanks for reporting this.
